//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurkcellDBw2Entities : DbContext
    {
        public TurkcellDBw2Entities()
            : base("name=TurkcellDBw2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Offers> Offers { get; set; }
        public DbSet<PosTransaction> PosTransaction { get; set; }
        public DbSet<VendorLogs> VendorLogs { get; set; }
        public DbSet<Vendors> Vendors { get; set; }
        public DbSet<WebServiceParameters> WebServiceParameters { get; set; }
        public DbSet<WebServices> WebServices { get; set; }
    }
}
