//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosTransaction
    {
        public int Id { get; set; }
        public string Msisdn { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int Location { get; set; }
        public string Campaign { get; set; }
        public string Income { get; set; }
        public string Amount { get; set; }
        public string CampaignType { get; set; }
        public string TrId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
