//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServices
    {
        public int Id { get; set; }
        public string ContextName { get; set; }
        public string WebServiceMethod { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
