//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.TestConsole.ClubMembershipServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubMembershipQueryResult", Namespace="http://schemas.datacontract.org/2004/07/wSrvLocatorLibrary")]
    [System.SerializableAttribute()]
    public partial class ClubMembershipQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MembersMsisdnListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MembersMsisdnList {
            get {
                return this.MembersMsisdnListField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersMsisdnListField, value) != true)) {
                    this.MembersMsisdnListField = value;
                    this.RaisePropertyChanged("MembersMsisdnList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClubMembershipServiceReference.IClubMembershipQueryService")]
    public interface IClubMembershipQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClubMembershipQueryService/BulkClubSearch", ReplyAction="http://tempuri.org/IClubMembershipQueryService/BulkClubSearchResponse")]
        wSrvBridge.TestConsole.ClubMembershipServiceReference.ClubMembershipQueryResult BulkClubSearch(string[] msisdnList, int clubId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClubMembershipQueryService/BulkClubSearch", ReplyAction="http://tempuri.org/IClubMembershipQueryService/BulkClubSearchResponse")]
        System.Threading.Tasks.Task<wSrvBridge.TestConsole.ClubMembershipServiceReference.ClubMembershipQueryResult> BulkClubSearchAsync(string[] msisdnList, int clubId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClubMembershipQueryServiceChannel : wSrvBridge.TestConsole.ClubMembershipServiceReference.IClubMembershipQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClubMembershipQueryServiceClient : System.ServiceModel.ClientBase<wSrvBridge.TestConsole.ClubMembershipServiceReference.IClubMembershipQueryService>, wSrvBridge.TestConsole.ClubMembershipServiceReference.IClubMembershipQueryService {
        
        public ClubMembershipQueryServiceClient() {
        }
        
        public ClubMembershipQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClubMembershipQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubMembershipQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubMembershipQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wSrvBridge.TestConsole.ClubMembershipServiceReference.ClubMembershipQueryResult BulkClubSearch(string[] msisdnList, int clubId) {
            return base.Channel.BulkClubSearch(msisdnList, clubId);
        }
        
        public System.Threading.Tasks.Task<wSrvBridge.TestConsole.ClubMembershipServiceReference.ClubMembershipQueryResult> BulkClubSearchAsync(string[] msisdnList, int clubId) {
            return base.Channel.BulkClubSearchAsync(msisdnList, clubId);
        }
    }
}
