//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcCampaigns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcCampaigns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcCampaigns", typeof(rsrcCampaigns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik .
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Girniz.
        /// </summary>
        public static string ContentReq {
            get {
                return ResourceManager.GetString("ContentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Bilgisi.
        /// </summary>
        public static string ExternalUrl {
            get {
                return ResourceManager.GetString("ExternalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık Giriniz.
        /// </summary>
        public static string HeaderReq {
            get {
                return ResourceManager.GetString("HeaderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Seçin.
        /// </summary>
        public static string ImageReq {
            get {
                return ResourceManager.GetString("ImageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece belirli kullanıcılar yararlanabilir..
        /// </summary>
        public static string IsUserCampaigns {
            get {
                return ResourceManager.GetString("IsUserCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Başlık.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Başlık Giriniz.
        /// </summary>
        public static string TitleReq {
            get {
                return ResourceManager.GetString("TitleReq", resourceCulture);
            }
        }
    }
}
