//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcPromoCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcPromoCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcPromoCodes", typeof(rsrcPromoCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi.
        /// </summary>
        public static string CatalogCategoriesId {
            get {
                return ResourceManager.GetString("CatalogCategoriesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi Girmelisiniz.
        /// </summary>
        public static string CatalogCategoriesIdReq {
            get {
                return ResourceManager.GetString("CatalogCategoriesIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog .
        /// </summary>
        public static string CatalogsId {
            get {
                return ResourceManager.GetString("CatalogsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Girmelisiniz.
        /// </summary>
        public static string CatalogsIdReq {
            get {
                return ResourceManager.GetString("CatalogsIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturan Girmelisiniz.
        /// </summary>
        public static string CreatedByReq {
            get {
                return ResourceManager.GetString("CreatedByReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Durumu.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Durumu Belirlemelisiniz.
        /// </summary>
        public static string IsUsedReq {
            get {
                return ResourceManager.GetString("IsUsedReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod.
        /// </summary>
        public static string PromoCodeName {
            get {
                return ResourceManager.GetString("PromoCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod Giriniz.
        /// </summary>
        public static string PromoCodeNameReq {
            get {
                return ResourceManager.GetString("PromoCodeNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod Tipi.
        /// </summary>
        public static string PromoCodeTypeId {
            get {
                return ResourceManager.GetString("PromoCodeTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod Tipi Giriniz.
        /// </summary>
        public static string PromoCodeTypeIdReq {
            get {
                return ResourceManager.GetString("PromoCodeTypeIdReq", resourceCulture);
            }
        }
    }
}
