//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcBanners {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcBanners() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcBanners", typeof(rsrcBanners).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi Zorunludur.
        /// </summary>
        public static string EndDateReq {
            get {
                return ResourceManager.GetString("EndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Adı.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Adı Zorunludur.
        /// </summary>
        public static string FileNameReq {
            get {
                return ResourceManager.GetString("FileNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterim Sırası.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterim Sırası Zorunludur.
        /// </summary>
        public static string OrderReq {
            get {
                return ResourceManager.GetString("OrderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        public static string PositionCode {
            get {
                return ResourceManager.GetString("PositionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon Kodu.
        /// </summary>
        public static string PositionCodeReq {
            get {
                return ResourceManager.GetString("PositionCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi Zorunludur.
        /// </summary>
        public static string StartDateReq {
            get {
                return ResourceManager.GetString("StartDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık Zorunludur.
        /// </summary>
        public static string TitleReq {
            get {
                return ResourceManager.GetString("TitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Bilgisi.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Bilgisi Zorunludur.
        /// </summary>
        public static string URLReq {
            get {
                return ResourceManager.GetString("URLReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencere Açlış Tipi.
        /// </summary>
        public static string WindowTypeCode {
            get {
                return ResourceManager.GetString("WindowTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencere Açlış Tipi Zorunludur.
        /// </summary>
        public static string WindowTypeCodeReq {
            get {
                return ResourceManager.GetString("WindowTypeCodeReq", resourceCulture);
            }
        }
    }
}
