//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcUsers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcUsers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcUsers", typeof(rsrcUsers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarhinizi eksik girdiniz.
        /// </summary>
        public static string BirthDateReq {
            get {
                return ResourceManager.GetString("BirthDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞEHİR.
        /// </summary>
        public static string CityCode {
            get {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir belirtiniz.
        /// </summary>
        public static string CityCodeReq {
            get {
                return ResourceManager.GetString("CityCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailinizi eksik girdiniz.
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CİNSİYET.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyetinizi belirtiniz.
        /// </summary>
        public static string GenderReq {
            get {
                return ResourceManager.GetString("GenderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Tarihi.
        /// </summary>
        public static string LoginDate {
            get {
                return ResourceManager.GetString("LoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş tarihini eksik girdiniz.
        /// </summary>
        public static string LoginDateReq {
            get {
                return ResourceManager.GetString("LoginDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Msisdn {
            get {
                return ResourceManager.GetString("Msisdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon giriniz.
        /// </summary>
        public static string MsisdnReq {
            get {
                return ResourceManager.GetString("MsisdnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADIN.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınızı eksik girdiniz.
        /// </summary>
        public static string NameReq {
            get {
                return ResourceManager.GetString("NameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOTOĞRAF.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf yükleyiniz.
        /// </summary>
        public static string ProfileImageReq {
            get {
                return ResourceManager.GetString("ProfileImageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz değer 2 ile 512 karakter arasında olmalıdır.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOYADIN.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınızı eksik girdiniz.
        /// </summary>
        public static string SurnameReq {
            get {
                return ResourceManager.GetString("SurnameReq", resourceCulture);
            }
        }
    }
}
