//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcEnumDisplays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcEnumDisplays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcEnumDisplays", typeof(rsrcEnumDisplays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        public static string BannerPosition_Global {
            get {
                return ResourceManager.GetString("BannerPosition_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sonrası.
        /// </summary>
        public static string BannerPosition_Login {
            get {
                return ResourceManager.GetString("BannerPosition_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Öncesi.
        /// </summary>
        public static string BannerPosition_UnLogin {
            get {
                return ResourceManager.GetString("BannerPosition_UnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süresi Geçmiş Ürünler.
        /// </summary>
        public static string CatalogDateEnd {
            get {
                return ResourceManager.GetString("CatalogDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanımda Olmayan Ürünler.
        /// </summary>
        public static string CatalogNotActive {
            get {
                return ResourceManager.GetString("CatalogNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Eklenen 100 Ürün.
        /// </summary>
        public static string CatalogOrderDateTop {
            get {
                return ResourceManager.GetString("CatalogOrderDateTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Yüksek Puanlı 100 Ürün.
        /// </summary>
        public static string CatalogOrderPoint {
            get {
                return ResourceManager.GetString("CatalogOrderPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Düşük Puanlı 100 Ürün.
        /// </summary>
        public static string CatalogOrderPointDown {
            get {
                return ResourceManager.GetString("CatalogOrderPointDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoğu En Fazla Olan 100 Ürün.
        /// </summary>
        public static string CatalogStock {
            get {
                return ResourceManager.GetString("CatalogStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoğu Tükenen Ürünler.
        /// </summary>
        public static string CatalogStockEmpty {
            get {
                return ResourceManager.GetString("CatalogStockEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Fazla Satılan Ürünler.
        /// </summary>
        public static string CatologBuyTop {
            get {
                return ResourceManager.GetString("CatologBuyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif Kullanıcılar.
        /// </summary>
        public static string GetDisableUser {
            get {
                return ResourceManager.GetString("GetDisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugün Login Olan Kullanıcılar.
        /// </summary>
        public static string GetToDayLogin {
            get {
                return ResourceManager.GetString("GetToDayLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugün Kayıt Olan Kullanıcılar.
        /// </summary>
        public static string GetToDayRecord {
            get {
                return ResourceManager.GetString("GetToDayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile Login Olan Kullanıcılar.
        /// </summary>
        public static string GetToFacebookLogin {
            get {
                return ResourceManager.GetString("GetToFacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile Kayıt Olan Kullanıcılar.
        /// </summary>
        public static string GetToFacebookRecord {
            get {
                return ResourceManager.GetString("GetToFacebookRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçen Ay Login Olan Kullanıcılar.
        /// </summary>
        public static string GetToLastMonthLogin {
            get {
                return ResourceManager.GetString("GetToLastMonthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçen Ayki Kayıtlar.
        /// </summary>
        public static string GetToLastMonthRecord {
            get {
                return ResourceManager.GetString("GetToLastMonthRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçen Hafta Login Olan Kullanıcılar.
        /// </summary>
        public static string GetToLastWeekLogin {
            get {
                return ResourceManager.GetString("GetToLastWeekLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçen Haftaki Kayıtlar.
        /// </summary>
        public static string GetToLastWeekRecord {
            get {
                return ResourceManager.GetString("GetToLastWeekRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkcell Süper Şifre İle Login Olanlar.
        /// </summary>
        public static string GetToSSOPassword {
            get {
                return ResourceManager.GetString("GetToSSOPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Ay Login Olan Kullanıcılar.
        /// </summary>
        public static string GetToThisMonthLogin {
            get {
                return ResourceManager.GetString("GetToThisMonthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Ay Kayıt Olan Kullanıcılar.
        /// </summary>
        public static string GetToThisMonthRecord {
            get {
                return ResourceManager.GetString("GetToThisMonthRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Hafta kayıt olan kullanıcılar.
        /// </summary>
        public static string GetToThisWeekLogin {
            get {
                return ResourceManager.GetString("GetToThisWeekLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Hafta Kayıt Olan Kullanıcılar.
        /// </summary>
        public static string GetToThisWeekRecord {
            get {
                return ResourceManager.GetString("GetToThisWeekRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        public static string OfferType_General {
            get {
                return ResourceManager.GetString("OfferType_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç.
        /// </summary>
        public static string OfferType_Startup {
            get {
                return ResourceManager.GetString("OfferType_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öneri.
        /// </summary>
        public static string OfferType_Suggestion {
            get {
                return ResourceManager.GetString("OfferType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _blank (yeni pencere).
        /// </summary>
        public static string WindowPosition_blank {
            get {
                return ResourceManager.GetString("WindowPosition_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _parent (üst frame).
        /// </summary>
        public static string WindowPosition_parent {
            get {
                return ResourceManager.GetString("WindowPosition_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _self (aynı sayfa).
        /// </summary>
        public static string WindowPosition_self {
            get {
                return ResourceManager.GetString("WindowPosition_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _top (frame dışı).
        /// </summary>
        public static string WindowPosition_top {
            get {
                return ResourceManager.GetString("WindowPosition_top", resourceCulture);
            }
        }
    }
}
