//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Com.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsrcCatalogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsrcCatalogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gnc2.Com.App_GlobalResources.rsrcCatalogs", typeof(rsrcCatalogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi.
        /// </summary>
        public static string CatalogCategoriesId {
            get {
                return ResourceManager.GetString("CatalogCategoriesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçim Yapmalısınız.
        /// </summary>
        public static string CatalogCategoriesIdReq {
            get {
                return ResourceManager.GetString("CatalogCategoriesIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koşullar - Şartlar.
        /// </summary>
        public static string CatalogCondition {
            get {
                return ResourceManager.GetString("CatalogCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koşullar - Şartlar Girmelisiniz.
        /// </summary>
        public static string CatalogConditionReq {
            get {
                return ResourceManager.GetString("CatalogConditionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kapanış Tarihi.
        /// </summary>
        public static string CatalogEndDate {
            get {
                return ResourceManager.GetString("CatalogEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kapanış Tarihi Girmelisiniz.
        /// </summary>
        public static string CatalogEndDateReq {
            get {
                return ResourceManager.GetString("CatalogEndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Özellikleri.
        /// </summary>
        public static string CatalogFeatures {
            get {
                return ResourceManager.GetString("CatalogFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Özellikleri Girmelisiniz.
        /// </summary>
        public static string CatalogFeaturesReq {
            get {
                return ResourceManager.GetString("CatalogFeaturesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Görseli.
        /// </summary>
        public static string CatalogImage {
            get {
                return ResourceManager.GetString("CatalogImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Görseli Girmelisiniz.
        /// </summary>
        public static string CatalogImageReq {
            get {
                return ResourceManager.GetString("CatalogImageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Adı.
        /// </summary>
        public static string CatalogName {
            get {
                return ResourceManager.GetString("CatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Adı Girmelisiniz.
        /// </summary>
        public static string CatalogNameReq {
            get {
                return ResourceManager.GetString("CatalogNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Puanı.
        /// </summary>
        public static string CatalogPoint {
            get {
                return ResourceManager.GetString("CatalogPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Puanı Girmelisiniz.
        /// </summary>
        public static string CatalogPointReq {
            get {
                return ResourceManager.GetString("CatalogPointReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Başlangıç Tarihi.
        /// </summary>
        public static string CatalogStartDate {
            get {
                return ResourceManager.GetString("CatalogStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Başlangıç Tarihi Girmelisiniz.
        /// </summary>
        public static string CatalogStartDateReq {
            get {
                return ResourceManager.GetString("CatalogStartDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi.
        /// </summary>
        public static string CatalogStockReq {
            get {
                return ResourceManager.GetString("CatalogStockReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Tipi.
        /// </summary>
        public static string CatalogTypeId {
            get {
                return ResourceManager.GetString("CatalogTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Tipi Giriniz.
        /// </summary>
        public static string CatalogTypeIdReq {
            get {
                return ResourceManager.GetString("CatalogTypeIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Adı.
        /// </summary>
        public static string CatalogTypeName {
            get {
                return ResourceManager.GetString("CatalogTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Adı Giriniz.
        /// </summary>
        public static string CatalogTypeNameReq {
            get {
                return ResourceManager.GetString("CatalogTypeNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi Girmelisiniz.
        /// </summary>
        public static string CategoryNameReq {
            get {
                return ResourceManager.GetString("CategoryNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Tipi.
        /// </summary>
        public static string ModuleTypeId {
            get {
                return ResourceManager.GetString("ModuleTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Tipi Giriniz.
        /// </summary>
        public static string CreatedByReq {
            get {
                return ResourceManager.GetString("CreatedByReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Yazı.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modül Adı Giriniz.
        /// </summary>
        public static string ModulTypeNameReq {
            get {
                return ResourceManager.GetString("ModulTypeNameReq", resourceCulture);
            }
        }
    }
}
