//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Service.ServiceQuery {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryRequest", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class QueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsisdnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msisdn {
            get {
                return this.MsisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.MsisdnField, value) != true)) {
                    this.MsisdnField = value;
                    this.RaisePropertyChanged("Msisdn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Service.Gigya")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceQuery.BaseWsModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceQuery.UserPoints))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallIdField, value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseWsModel", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceQuery.UserPoints))]
    public partial class BaseWsModel : Gnc2.Service.ServiceQuery.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPoints", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class UserPoints : Gnc2.Service.ServiceQuery.BaseWsModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsTotal {
            get {
                return this.PointsTotalField;
            }
            set {
                if ((this.PointsTotalField.Equals(value) != true)) {
                    this.PointsTotalField = value;
                    this.RaisePropertyChanged("PointsTotal");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceQuery.IQuery")]
    public interface IQuery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/IQuery/GetUserTotalPointsResponse")]
        Gnc2.Service.ServiceQuery.UserPoints GetUserTotalPoints(Gnc2.Service.ServiceQuery.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/IQuery/GetUserTotalPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceQuery.UserPoints> GetUserTotalPointsAsync(Gnc2.Service.ServiceQuery.QueryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Json_x002F_GetUserTotalPoints) of message Json_x002F_GetUserTotalPointsRequest does not match the default value (JsonGetUserTotalPoints)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuery/Json/GetUserTotalPoints", ReplyAction="http://tempuri.org/IQuery/Json/GetUserTotalPointsResponse")]
        Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse JsonGetUserTotalPoints(Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuery/Json/GetUserTotalPoints", ReplyAction="http://tempuri.org/IQuery/Json/GetUserTotalPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse> JsonGetUserTotalPointsAsync(Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetUserTotalPoints", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetUserTotalPointsRequest {
        
        public JsonGetUserTotalPointsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetUserTotalPointsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetUserTotalPointsResponse {
        
        public JsonGetUserTotalPointsResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryChannel : Gnc2.Service.ServiceQuery.IQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryClient : System.ServiceModel.ClientBase<Gnc2.Service.ServiceQuery.IQuery>, Gnc2.Service.ServiceQuery.IQuery {
        
        public QueryClient() {
        }
        
        public QueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gnc2.Service.ServiceQuery.UserPoints GetUserTotalPoints(Gnc2.Service.ServiceQuery.QueryRequest request) {
            return base.Channel.GetUserTotalPoints(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceQuery.UserPoints> GetUserTotalPointsAsync(Gnc2.Service.ServiceQuery.QueryRequest request) {
            return base.Channel.GetUserTotalPointsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse Gnc2.Service.ServiceQuery.IQuery.JsonGetUserTotalPoints(Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest request) {
            return base.Channel.JsonGetUserTotalPoints(request);
        }
        
        public void JsonGetUserTotalPoints() {
            Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest inValue = new Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest();
            Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse retVal = ((Gnc2.Service.ServiceQuery.IQuery)(this)).JsonGetUserTotalPoints(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse> Gnc2.Service.ServiceQuery.IQuery.JsonGetUserTotalPointsAsync(Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest request) {
            return base.Channel.JsonGetUserTotalPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsResponse> JsonGetUserTotalPointsAsync() {
            Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest inValue = new Gnc2.Service.ServiceQuery.JsonGetUserTotalPointsRequest();
            return ((Gnc2.Service.ServiceQuery.IQuery)(this)).JsonGetUserTotalPointsAsync(inValue);
        }
    }
}
