//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gigya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GigyaLogs
    {
        public System.Guid Id { get; set; }
        public string ApiMethod { get; set; }
        public string ApiKey { get; set; }
        public string ClientParams { get; set; }
        public string Response { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> VendorId { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string CallId { get; set; }
    }
}
