//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Service.ServiceSmsQuery {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryRequest", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsisdnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msisdn {
            get {
                return this.MsisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.MsisdnField, value) != true)) {
                    this.MsisdnField = value;
                    this.RaisePropertyChanged("Msisdn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Service.Gigya")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceSmsQuery.BaseWsModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceSmsQuery.SmsQueryResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallIdField, value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseWsModel", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceSmsQuery.SmsQueryResponse))]
    public partial class BaseWsModel : Gnc2.Service.ServiceSmsQuery.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryActionResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryActionResponse : Gnc2.Service.ServiceSmsQuery.BaseWsModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionPoints {
            get {
                return this.ActionPointsField;
            }
            set {
                if ((this.ActionPointsField.Equals(value) != true)) {
                    this.ActionPointsField = value;
                    this.RaisePropertyChanged("ActionPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsText {
            get {
                return this.SmsTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTextField, value) != true)) {
                    this.SmsTextField = value;
                    this.RaisePropertyChanged("SmsText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryResponse : Gnc2.Service.ServiceSmsQuery.BaseWsModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsText {
            get {
                return this.SmsTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTextField, value) != true)) {
                    this.SmsTextField = value;
                    this.RaisePropertyChanged("SmsText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPoints {
            get {
                return this.TotalPointsField;
            }
            set {
                if ((this.TotalPointsField.Equals(value) != true)) {
                    this.TotalPointsField = value;
                    this.RaisePropertyChanged("TotalPoints");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryActionRequest", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryActionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSmsQuery.ISmsQuery")]
    public interface ISmsQuery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetUserTotalPointsResponse")]
        Gnc2.Service.ServiceSmsQuery.SmsQueryResponse GetUserTotalPoints(Gnc2.Service.ServiceSmsQuery.SmsQueryRequest data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetUserTotalPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.SmsQueryResponse> GetUserTotalPointsAsync(Gnc2.Service.ServiceSmsQuery.SmsQueryRequest data);
        
        // CODEGEN: Generating message contract since the wrapper name (Json_x002F_GetUserTotalPoints) of message Json_x002F_GetUserTotalPointsRequest does not match the default value (JsonGetUserTotalPoints)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/Json/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/Json/GetUserTotalPointsResponse")]
        Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse JsonGetUserTotalPoints(Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/Json/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/Json/GetUserTotalPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse> JsonGetUserTotalPointsAsync(Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetActionPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetActionPointsResponse")]
        Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse GetActionPoints(Gnc2.Service.ServiceSmsQuery.SmsQueryActionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetActionPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetActionPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse> GetActionPointsAsync(Gnc2.Service.ServiceSmsQuery.SmsQueryActionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Json_x002F_GetActionPoints) of message Json_x002F_GetActionPointsRequest does not match the default value (JsonGetActionPoints)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/Json/GetActionPoints", ReplyAction="http://tempuri.org/ISmsQuery/Json/GetActionPointsResponse")]
        Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse JsonGetActionPoints(Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/Json/GetActionPoints", ReplyAction="http://tempuri.org/ISmsQuery/Json/GetActionPointsResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse> JsonGetActionPointsAsync(Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetUserTotalPoints", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetUserTotalPointsRequest {
        
        public JsonGetUserTotalPointsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetUserTotalPointsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetUserTotalPointsResponse {
        
        public JsonGetUserTotalPointsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetActionPoints", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetActionPointsRequest {
        
        public JsonGetActionPointsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/GetActionPointsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonGetActionPointsResponse {
        
        public JsonGetActionPointsResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsQueryChannel : Gnc2.Service.ServiceSmsQuery.ISmsQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsQueryClient : System.ServiceModel.ClientBase<Gnc2.Service.ServiceSmsQuery.ISmsQuery>, Gnc2.Service.ServiceSmsQuery.ISmsQuery {
        
        public SmsQueryClient() {
        }
        
        public SmsQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gnc2.Service.ServiceSmsQuery.SmsQueryResponse GetUserTotalPoints(Gnc2.Service.ServiceSmsQuery.SmsQueryRequest data) {
            return base.Channel.GetUserTotalPoints(data);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.SmsQueryResponse> GetUserTotalPointsAsync(Gnc2.Service.ServiceSmsQuery.SmsQueryRequest data) {
            return base.Channel.GetUserTotalPointsAsync(data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse Gnc2.Service.ServiceSmsQuery.ISmsQuery.JsonGetUserTotalPoints(Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest request) {
            return base.Channel.JsonGetUserTotalPoints(request);
        }
        
        public void JsonGetUserTotalPoints() {
            Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest inValue = new Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest();
            Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse retVal = ((Gnc2.Service.ServiceSmsQuery.ISmsQuery)(this)).JsonGetUserTotalPoints(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse> Gnc2.Service.ServiceSmsQuery.ISmsQuery.JsonGetUserTotalPointsAsync(Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest request) {
            return base.Channel.JsonGetUserTotalPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsResponse> JsonGetUserTotalPointsAsync() {
            Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest inValue = new Gnc2.Service.ServiceSmsQuery.JsonGetUserTotalPointsRequest();
            return ((Gnc2.Service.ServiceSmsQuery.ISmsQuery)(this)).JsonGetUserTotalPointsAsync(inValue);
        }
        
        public Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse GetActionPoints(Gnc2.Service.ServiceSmsQuery.SmsQueryActionRequest request) {
            return base.Channel.GetActionPoints(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.SmsQueryActionResponse> GetActionPointsAsync(Gnc2.Service.ServiceSmsQuery.SmsQueryActionRequest request) {
            return base.Channel.GetActionPointsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse Gnc2.Service.ServiceSmsQuery.ISmsQuery.JsonGetActionPoints(Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest request) {
            return base.Channel.JsonGetActionPoints(request);
        }
        
        public void JsonGetActionPoints() {
            Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest inValue = new Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest();
            Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse retVal = ((Gnc2.Service.ServiceSmsQuery.ISmsQuery)(this)).JsonGetActionPoints(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse> Gnc2.Service.ServiceSmsQuery.ISmsQuery.JsonGetActionPointsAsync(Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest request) {
            return base.Channel.JsonGetActionPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsResponse> JsonGetActionPointsAsync() {
            Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest inValue = new Gnc2.Service.ServiceSmsQuery.JsonGetActionPointsRequest();
            return ((Gnc2.Service.ServiceSmsQuery.ISmsQuery)(this)).JsonGetActionPointsAsync(inValue);
        }
    }
}
