//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Sms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryRequest", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsisdnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msisdn {
            get {
                return this.MsisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.MsisdnField, value) != true)) {
                    this.MsisdnField = value;
                    this.RaisePropertyChanged("Msisdn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseWsModel", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.Sms.SmsQueryResponse))]
    public partial class BaseWsModel : w2.Service.Gigya.BaseResponse, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsQueryResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Ws")]
    [System.SerializableAttribute()]
    public partial class SmsQueryResponse : TestConsole.Sms.BaseWsModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsTotal {
            get {
                return this.PointsTotalField;
            }
            set {
                if ((this.PointsTotalField.Equals(value) != true)) {
                    this.PointsTotalField = value;
                    this.RaisePropertyChanged("PointsTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsText {
            get {
                return this.SmsTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTextField, value) != true)) {
                    this.SmsTextField = value;
                    this.RaisePropertyChanged("SmsText");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sms.ISmsQuery")]
    public interface ISmsQuery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetUserTotalPointsResponse")]
        TestConsole.Sms.SmsQueryResponse GetUserTotalPoints(TestConsole.Sms.SmsQueryRequest data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsQuery/GetUserTotalPoints", ReplyAction="http://tempuri.org/ISmsQuery/GetUserTotalPointsResponse")]
        System.Threading.Tasks.Task<TestConsole.Sms.SmsQueryResponse> GetUserTotalPointsAsync(TestConsole.Sms.SmsQueryRequest data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsQueryChannel : TestConsole.Sms.ISmsQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsQueryClient : System.ServiceModel.ClientBase<TestConsole.Sms.ISmsQuery>, TestConsole.Sms.ISmsQuery {
        
        public SmsQueryClient() {
        }
        
        public SmsQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestConsole.Sms.SmsQueryResponse GetUserTotalPoints(TestConsole.Sms.SmsQueryRequest data) {
            return base.Channel.GetUserTotalPoints(data);
        }
        
        public System.Threading.Tasks.Task<TestConsole.Sms.SmsQueryResponse> GetUserTotalPointsAsync(TestConsole.Sms.SmsQueryRequest data) {
            return base.Channel.GetUserTotalPointsAsync(data);
        }
    }
}
