//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.TestConsole.SmsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsServiceResult", Namespace="http://schemas.datacontract.org/2004/07/wSrvLocatorLibrary")]
    [System.SerializableAttribute()]
    public partial class SmsServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.ISmsService")]
    public interface ISmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendSms", ReplyAction="http://tempuri.org/ISmsService/SendSmsResponse")]
        wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult SendSms(string AppId, string Msisdn, string SmsText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendSms", ReplyAction="http://tempuri.org/ISmsService/SendSmsResponse")]
        System.Threading.Tasks.Task<wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult> SendSmsAsync(string AppId, string Msisdn, string SmsText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/NewTicket", ReplyAction="http://tempuri.org/ISmsService/NewTicketResponse")]
        wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult NewTicket(string AppId, string Msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/NewTicket", ReplyAction="http://tempuri.org/ISmsService/NewTicketResponse")]
        System.Threading.Tasks.Task<wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult> NewTicketAsync(string AppId, string Msisdn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsServiceChannel : wSrvBridge.TestConsole.SmsServiceReference.ISmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceClient : System.ServiceModel.ClientBase<wSrvBridge.TestConsole.SmsServiceReference.ISmsService>, wSrvBridge.TestConsole.SmsServiceReference.ISmsService {
        
        public SmsServiceClient() {
        }
        
        public SmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult SendSms(string AppId, string Msisdn, string SmsText) {
            return base.Channel.SendSms(AppId, Msisdn, SmsText);
        }
        
        public System.Threading.Tasks.Task<wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult> SendSmsAsync(string AppId, string Msisdn, string SmsText) {
            return base.Channel.SendSmsAsync(AppId, Msisdn, SmsText);
        }
        
        public wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult NewTicket(string AppId, string Msisdn) {
            return base.Channel.NewTicket(AppId, Msisdn);
        }
        
        public System.Threading.Tasks.Task<wSrvBridge.TestConsole.SmsServiceReference.SmsServiceResult> NewTicketAsync(string AppId, string Msisdn) {
            return base.Channel.NewTicketAsync(AppId, Msisdn);
        }
    }
}
