//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvConnector.PennaSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.pennaltd.com/", ConfigurationName="PennaSmsService.EventsSoap")]
    public interface EventsSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://ws.pennaltd.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pennaltd.com/insertNewTicket", ReplyAction="*")]
        wSrvConnector.PennaSmsService.insertNewTicketResponse insertNewTicket(wSrvConnector.PennaSmsService.insertNewTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pennaltd.com/insertNewTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.insertNewTicketResponse> insertNewTicketAsync(wSrvConnector.PennaSmsService.insertNewTicketRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://ws.pennaltd.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pennaltd.com/sendSms", ReplyAction="*")]
        wSrvConnector.PennaSmsService.sendSmsResponse sendSms(wSrvConnector.PennaSmsService.sendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.pennaltd.com/sendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.sendSmsResponse> sendSmsAsync(wSrvConnector.PennaSmsService.sendSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertNewTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertNewTicket", Namespace="http://ws.pennaltd.com/", Order=0)]
        public wSrvConnector.PennaSmsService.insertNewTicketRequestBody Body;
        
        public insertNewTicketRequest() {
        }
        
        public insertNewTicketRequest(wSrvConnector.PennaSmsService.insertNewTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.pennaltd.com/")]
    public partial class insertNewTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msisdn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string param3;
        
        public insertNewTicketRequestBody() {
        }
        
        public insertNewTicketRequestBody(string user, string pass, string appId, string msisdn, string param1, string param2, string param3) {
            this.user = user;
            this.pass = pass;
            this.appId = appId;
            this.msisdn = msisdn;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertNewTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertNewTicketResponse", Namespace="http://ws.pennaltd.com/", Order=0)]
        public wSrvConnector.PennaSmsService.insertNewTicketResponseBody Body;
        
        public insertNewTicketResponse() {
        }
        
        public insertNewTicketResponse(wSrvConnector.PennaSmsService.insertNewTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.pennaltd.com/")]
    public partial class insertNewTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertNewTicketResult;
        
        public insertNewTicketResponseBody() {
        }
        
        public insertNewTicketResponseBody(string insertNewTicketResult) {
            this.insertNewTicketResult = insertNewTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSms", Namespace="http://ws.pennaltd.com/", Order=0)]
        public wSrvConnector.PennaSmsService.sendSmsRequestBody Body;
        
        public sendSmsRequest() {
        }
        
        public sendSmsRequest(wSrvConnector.PennaSmsService.sendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.pennaltd.com/")]
    public partial class sendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msisdn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string param2;
        
        public sendSmsRequestBody() {
        }
        
        public sendSmsRequestBody(string user, string pass, string appId, string msisdn, string smsText, string param1, string param2) {
            this.user = user;
            this.pass = pass;
            this.appId = appId;
            this.msisdn = msisdn;
            this.smsText = smsText;
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSmsResponse", Namespace="http://ws.pennaltd.com/", Order=0)]
        public wSrvConnector.PennaSmsService.sendSmsResponseBody Body;
        
        public sendSmsResponse() {
        }
        
        public sendSmsResponse(wSrvConnector.PennaSmsService.sendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.pennaltd.com/")]
    public partial class sendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendSmsResult;
        
        public sendSmsResponseBody() {
        }
        
        public sendSmsResponseBody(string sendSmsResult) {
            this.sendSmsResult = sendSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventsSoapChannel : wSrvConnector.PennaSmsService.EventsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventsSoapClient : System.ServiceModel.ClientBase<wSrvConnector.PennaSmsService.EventsSoap>, wSrvConnector.PennaSmsService.EventsSoap {
        
        public EventsSoapClient() {
        }
        
        public EventsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wSrvConnector.PennaSmsService.insertNewTicketResponse wSrvConnector.PennaSmsService.EventsSoap.insertNewTicket(wSrvConnector.PennaSmsService.insertNewTicketRequest request) {
            return base.Channel.insertNewTicket(request);
        }
        
        public string insertNewTicket(string user, string pass, string appId, string msisdn, string param1, string param2, string param3) {
            wSrvConnector.PennaSmsService.insertNewTicketRequest inValue = new wSrvConnector.PennaSmsService.insertNewTicketRequest();
            inValue.Body = new wSrvConnector.PennaSmsService.insertNewTicketRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.appId = appId;
            inValue.Body.msisdn = msisdn;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            wSrvConnector.PennaSmsService.insertNewTicketResponse retVal = ((wSrvConnector.PennaSmsService.EventsSoap)(this)).insertNewTicket(inValue);
            return retVal.Body.insertNewTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.insertNewTicketResponse> wSrvConnector.PennaSmsService.EventsSoap.insertNewTicketAsync(wSrvConnector.PennaSmsService.insertNewTicketRequest request) {
            return base.Channel.insertNewTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.insertNewTicketResponse> insertNewTicketAsync(string user, string pass, string appId, string msisdn, string param1, string param2, string param3) {
            wSrvConnector.PennaSmsService.insertNewTicketRequest inValue = new wSrvConnector.PennaSmsService.insertNewTicketRequest();
            inValue.Body = new wSrvConnector.PennaSmsService.insertNewTicketRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.appId = appId;
            inValue.Body.msisdn = msisdn;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            return ((wSrvConnector.PennaSmsService.EventsSoap)(this)).insertNewTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wSrvConnector.PennaSmsService.sendSmsResponse wSrvConnector.PennaSmsService.EventsSoap.sendSms(wSrvConnector.PennaSmsService.sendSmsRequest request) {
            return base.Channel.sendSms(request);
        }
        
        public string sendSms(string user, string pass, string appId, string msisdn, string smsText, string param1, string param2) {
            wSrvConnector.PennaSmsService.sendSmsRequest inValue = new wSrvConnector.PennaSmsService.sendSmsRequest();
            inValue.Body = new wSrvConnector.PennaSmsService.sendSmsRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.appId = appId;
            inValue.Body.msisdn = msisdn;
            inValue.Body.smsText = smsText;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            wSrvConnector.PennaSmsService.sendSmsResponse retVal = ((wSrvConnector.PennaSmsService.EventsSoap)(this)).sendSms(inValue);
            return retVal.Body.sendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.sendSmsResponse> wSrvConnector.PennaSmsService.EventsSoap.sendSmsAsync(wSrvConnector.PennaSmsService.sendSmsRequest request) {
            return base.Channel.sendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<wSrvConnector.PennaSmsService.sendSmsResponse> sendSmsAsync(string user, string pass, string appId, string msisdn, string smsText, string param1, string param2) {
            wSrvConnector.PennaSmsService.sendSmsRequest inValue = new wSrvConnector.PennaSmsService.sendSmsRequest();
            inValue.Body = new wSrvConnector.PennaSmsService.sendSmsRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.appId = appId;
            inValue.Body.msisdn = msisdn;
            inValue.Body.smsText = smsText;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            return ((wSrvConnector.PennaSmsService.EventsSoap)(this)).sendSmsAsync(inValue);
        }
    }
}
