//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QDBOfferList
    {
        public int Id { get; set; }
        public string OfferId { get; set; }
        public string OfferUniqueName { get; set; }
        public bool FilterStatus { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
