//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QDBValueTracker
    {
        public int Id { get; set; }
        public System.DateTime LastTimestamp { get; set; }
        public int LastProvId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
