//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int Id { get; set; }
        public string LogLevel { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string Naming { get; set; }
        public string Operation { get; set; }
        public string ExceptionType { get; set; }
        public int ActivePlatform { get; set; }
        public string ResponseData { get; set; }
        public string Referrer { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
