//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvBridge.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class srvBridgeDbContainer : DbContext
    {
        public srvBridgeDbContainer()
            : base("name=srvBridgeDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<QDBValueTracker> QDBValueTrackers { get; set; }
        public DbSet<WebService> WebServices { get; set; }
        public DbSet<ServiceLog> ServiceLogs { get; set; }
        public DbSet<QDBOfferList> QDBOfferList { get; set; }
    
        public virtual ObjectResult<uspGetMeteringTransactions_Result> uspGetMeteringTransactions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetMeteringTransactions_Result>("uspGetMeteringTransactions");
        }
    }
}
