//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Kendo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kendo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Kendo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ve.
        /// </summary>
        internal static string FilterMsgAnd {
            get {
                return ResourceManager.GetString("FilterMsgAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string FilterMsgClear {
            get {
                return ResourceManager.GetString("FilterMsgClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        internal static string FilterMsgFilter {
            get {
                return ResourceManager.GetString("FilterMsgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtreleme Seçenekleri.
        /// </summary>
        internal static string FilterMsgInfo {
            get {
                return ResourceManager.GetString("FilterMsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklemede.
        /// </summary>
        internal static string FilterMsgIsFalse {
            get {
                return ResourceManager.GetString("FilterMsgIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayında.
        /// </summary>
        internal static string FilterMsgIsTrue {
            get {
                return ResourceManager.GetString("FilterMsgIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veya.
        /// </summary>
        internal static string FilterMsgOr {
            get {
                return ResourceManager.GetString("FilterMsgOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşitse.
        /// </summary>
        internal static string FilterOpDateIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyükse.
        /// </summary>
        internal static string FilterOpDateIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterOpDateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyü ve eşitse.
        /// </summary>
        internal static string FilterOpDateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçükse.
        /// </summary>
        internal static string FilterOpDateIsLessThan {
            get {
                return ResourceManager.GetString("FilterOpDateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük ve eşitse.
        /// </summary>
        internal static string FilterOpDateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşit Değilse.
        /// </summary>
        internal static string FilterOpDateIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpDateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşitse.
        /// </summary>
        internal static string FilterOpNumIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyükse.
        /// </summary>
        internal static string FilterOpNumIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterOpNumIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyü ve eşitse.
        /// </summary>
        internal static string FilterOpNumIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçükse.
        /// </summary>
        internal static string FilterOpNumIsLessThan {
            get {
                return ResourceManager.GetString("FilterOpNumIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük ve eşitse.
        /// </summary>
        internal static string FilterOpNumIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşit Değilse.
        /// </summary>
        internal static string FilterOpNumIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpNumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeren.
        /// </summary>
        internal static string FilterOpStrContains {
            get {
                return ResourceManager.GetString("FilterOpStrContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçermeyen.
        /// </summary>
        internal static string FilterOpStrDoesNotContain {
            get {
                return ResourceManager.GetString("FilterOpStrDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İle biten.
        /// </summary>
        internal static string FilterOpStrEndsWith {
            get {
                return ResourceManager.GetString("FilterOpStrEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşitse.
        /// </summary>
        internal static string FilterOpStrIsEqualTo {
            get {
                return ResourceManager.GetString("FilterOpStrIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşit Değilse.
        /// </summary>
        internal static string FilterOpStrIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOpStrIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İle başlayan.
        /// </summary>
        internal static string FilterOpStrStartsWith {
            get {
                return ResourceManager.GetString("FilterOpStrStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalın.
        /// </summary>
        internal static string HtmlEditorBold {
            get {
                return ResourceManager.GetString("HtmlEditorBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link ekle.
        /// </summary>
        internal static string HtmlEditorCreateLink {
            get {
                return ResourceManager.GetString("HtmlEditorCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan Font.
        /// </summary>
        internal static string HtmlEditorFontNameInherit {
            get {
                return ResourceManager.GetString("HtmlEditorFontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan Boyut.
        /// </summary>
        internal static string HtmlEditorFontSizeInherit {
            get {
                return ResourceManager.GetString("HtmlEditorFontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim ekle.
        /// </summary>
        internal static string HtmlEditorInsertImage {
            get {
                return ResourceManager.GetString("HtmlEditorInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metni ortala.
        /// </summary>
        internal static string HtmlEditorJustifyCenter {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İki yana dayalı.
        /// </summary>
        internal static string HtmlEditorJustifyFull {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sola dayalı.
        /// </summary>
        internal static string HtmlEditorJustifyLeft {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağa dayalı.
        /// </summary>
        internal static string HtmlEditorJustifyRight {
            get {
                return ResourceManager.GetString("HtmlEditorJustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üstü Çizili.
        /// </summary>
        internal static string HtmlEditorStrikethrough {
            get {
                return ResourceManager.GetString("HtmlEditorStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altı Çizili.
        /// </summary>
        internal static string HtmlEditorUnderline {
            get {
                return ResourceManager.GetString("HtmlEditorUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linki kaldır.
        /// </summary>
        internal static string HtmlEditorUnlink {
            get {
                return ResourceManager.GetString("HtmlEditorUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} ile {1}) &lt;b&gt;Toplam: &lt;/b&gt;{2}.
        /// </summary>
        internal static string PagerDisplay {
            get {
                return ResourceManager.GetString("PagerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Bulunamadı.
        /// </summary>
        internal static string PagerEmpty {
            get {
                return ResourceManager.GetString("PagerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk.
        /// </summary>
        internal static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PagerItemsPerPage {
            get {
                return ResourceManager.GetString("PagerItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / {0}.
        /// </summary>
        internal static string PagerOf {
            get {
                return ResourceManager.GetString("PagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa:.
        /// </summary>
        internal static string PagerPage {
            get {
                return ResourceManager.GetString("PagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string PagerRefresh {
            get {
                return ResourceManager.GetString("PagerRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazgeç.
        /// </summary>
        internal static string UploadCancel {
            get {
                return ResourceManager.GetString("UploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görseli buraya sürükle....
        /// </summary>
        internal static string UploadDropFiles {
            get {
                return ResourceManager.GetString("UploadDropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldır.
        /// </summary>
        internal static string UploadRemove {
            get {
                return ResourceManager.GetString("UploadRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Dene.
        /// </summary>
        internal static string UploadRetry {
            get {
                return ResourceManager.GetString("UploadRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gözat.
        /// </summary>
        internal static string UploadSelect {
            get {
                return ResourceManager.GetString("UploadSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Dosyaları Yükle.
        /// </summary>
        internal static string UploadSelectedFiles {
            get {
                return ResourceManager.GetString("UploadSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarısız.
        /// </summary>
        internal static string UploadStatusFailed {
            get {
                return ResourceManager.GetString("UploadStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Yüklendi.
        /// </summary>
        internal static string UploadStatusUploaded {
            get {
                return ResourceManager.GetString("UploadStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleniyor....
        /// </summary>
        internal static string UploadStatusUploading {
            get {
                return ResourceManager.GetString("UploadStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin Dosyasını buraya sürükle....
        /// </summary>
        internal static string UploadTextFiles {
            get {
                return ResourceManager.GetString("UploadTextFiles", resourceCulture);
            }
        }
    }
}
