//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notices", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Detay.
        /// </summary>
        internal static string CatalogCondition {
            get {
                return ResourceManager.GetString("CatalogCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Girmelisiniz!.
        /// </summary>
        internal static string CatalogConditionReq {
            get {
                return ResourceManager.GetString("CatalogConditionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Kategorisi.
        /// </summary>
        internal static string CatalogFeatures {
            get {
                return ResourceManager.GetString("CatalogFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Bırakılmaz !.
        /// </summary>
        internal static string CatalogFeaturesReq {
            get {
                return ResourceManager.GetString("CatalogFeaturesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİR HATA OLUŞTU! Doğru seçimleri yaptığınıza emin olunuz..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata !.
        /// </summary>
        internal static string ErrorMessageRsrcKey {
            get {
                return ResourceManager.GetString("ErrorMessageRsrcKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Yazı.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Bırakılmaz !.
        /// </summary>
        internal static string HeaderReq {
            get {
                return ResourceManager.GetString("HeaderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ YAPILAMADI!.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek kayıt bulunamadı.
        /// </summary>
        internal static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz alınmıştır, SMS ile bilgilendirileceksiniz..
        /// </summary>
        internal static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedildi!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin Belgesi.
        /// </summary>
        internal static string TextFileUpload {
            get {
                return ResourceManager.GetString("TextFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Metin Belgesi Seçmelisiniz.
        /// </summary>
        internal static string TextFileUploadReq {
            get {
                return ResourceManager.GetString("TextFileUploadReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt uzantılı bir metin dosyası seçmelisiniz..
        /// </summary>
        internal static string TextfileUploadType {
            get {
                return ResourceManager.GetString("TextfileUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel yüklenirken hata oluştur.
        /// </summary>
        internal static string UploadImgErr {
            get {
                return ResourceManager.GetString("UploadImgErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı kullanımda. Başka bir kullanıcı adı seçiniz..
        /// </summary>
        internal static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay içeriğini giriniz.
        /// </summary>
        internal static string ValContentDetailReq {
            get {
                return ResourceManager.GetString("ValContentDetailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay içeriği giriniz.
        /// </summary>
        internal static string ValFaqContentReq {
            get {
                return ResourceManager.GetString("ValFaqContentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel Seçiniz.
        /// </summary>
        internal static string ValFileUploadReq {
            get {
                return ResourceManager.GetString("ValFileUploadReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: 2MB olmalı!.
        /// </summary>
        internal static string ValFileUploadSize {
            get {
                return ResourceManager.GetString("ValFileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir resim dosyası seçiniz.
        /// </summary>
        internal static string ValFileUploadType {
            get {
                return ResourceManager.GetString("ValFileUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon seçiniz.
        /// </summary>
        internal static string ValPositionCodeReq {
            get {
                return ResourceManager.GetString("ValPositionCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max : 1 MB olmalı! .
        /// </summary>
        internal static string ValTextFileUploadSize {
            get {
                return ResourceManager.GetString("ValTextFileUploadSize", resourceCulture);
            }
        }
    }
}
