//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        internal static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        internal static string AdminUserList {
            get {
                return ResourceManager.GetString("AdminUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Yönetimi.
        /// </summary>
        internal static string Banners {
            get {
                return ResourceManager.GetString("Banners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalar.
        /// </summary>
        internal static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Yönetimi.
        /// </summary>
        internal static string CatalogCategories {
            get {
                return ResourceManager.GetString("CatalogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Yönetimi.
        /// </summary>
        internal static string Catalogs {
            get {
                return ResourceManager.GetString("Catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog Promo Kod Tipi.
        /// </summary>
        internal static string CatalogType {
            get {
                return ResourceManager.GetString("CatalogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Yönetimi.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sık Sorulan Sorular.
        /// </summary>
        internal static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN YÖNETİMİ.
        /// </summary>
        internal static string grpAdmin {
            get {
                return ResourceManager.GetString("grpAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İÇERİK YÖNETİMİ.
        /// </summary>
        internal static string grpContent {
            get {
                return ResourceManager.GetString("grpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG YÖNETİMİ.
        /// </summary>
        internal static string grpLog {
            get {
                return ResourceManager.GetString("grpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETRE YÖNETİMİ.
        /// </summary>
        internal static string grpParameter {
            get {
                return ResourceManager.GetString("grpParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Yönetimi.
        /// </summary>
        internal static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Bilgilerim.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod Arşivi.
        /// </summary>
        internal static string PromoCodeArchives {
            get {
                return ResourceManager.GetString("PromoCodeArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kodları.
        /// </summary>
        internal static string PromoCodes {
            get {
                return ResourceManager.GetString("PromoCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Kod Tipleri.
        /// </summary>
        internal static string PromoCodeTypes {
            get {
                return ResourceManager.GetString("PromoCodeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL Gönderim Miktarları.
        /// </summary>
        internal static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Detayı.
        /// </summary>
        internal static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Üyelik Kontrolü.
        /// </summary>
        internal static string UserRegisterControl {
            get {
                return ResourceManager.GetString("UserRegisterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Servis Log&apos; ları.
        /// </summary>
        internal static string WebServiceLogs {
            get {
                return ResourceManager.GetString("WebServiceLogs", resourceCulture);
            }
        }
    }
}
