//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSrvConnector.PermissionServicesStb2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermQueryExtResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermQueryExtResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> csourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string csourceDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modifyUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptout {
            get {
                return this.coptoutField;
            }
            set {
                if ((this.coptoutField.Equals(value) != true)) {
                    this.coptoutField = value;
                    this.RaisePropertyChanged("coptout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> csource {
            get {
                return this.csourceField;
            }
            set {
                if ((this.csourceField.Equals(value) != true)) {
                    this.csourceField = value;
                    this.RaisePropertyChanged("csource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string csourceDesc {
            get {
                return this.csourceDescField;
            }
            set {
                if ((object.ReferenceEquals(this.csourceDescField, value) != true)) {
                    this.csourceDescField = value;
                    this.RaisePropertyChanged("csourceDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string modifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                if ((object.ReferenceEquals(this.modifyDateField, value) != true)) {
                    this.modifyDateField = value;
                    this.RaisePropertyChanged("modifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string modifyUser {
            get {
                return this.modifyUserField;
            }
            set {
                if ((object.ReferenceEquals(this.modifyUserField, value) != true)) {
                    this.modifyUserField = value;
                    this.RaisePropertyChanged("modifyUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermWriteResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermWriteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://service.permission.ccrl.cusman.turkcell.com", ItemName="string")]
    [System.SerializableAttribute()]
    internal class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermQueryResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptout {
            get {
                return this.coptoutField;
            }
            set {
                if ((this.coptoutField.Equals(value) != true)) {
                    this.coptoutField = value;
                    this.RaisePropertyChanged("coptout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvertisementPerm", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class AdvertisementPerm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bulkSmsPermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] busPartnerPermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.ChannelPermQuery[] channelPermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] mobilMarketingPermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] turkcellPermsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int bulkSmsPerm {
            get {
                return this.bulkSmsPermField;
            }
            set {
                if ((this.bulkSmsPermField.Equals(value) != true)) {
                    this.bulkSmsPermField = value;
                    this.RaisePropertyChanged("bulkSmsPerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] busPartnerPerms {
            get {
                return this.busPartnerPermsField;
            }
            set {
                if ((object.ReferenceEquals(this.busPartnerPermsField, value) != true)) {
                    this.busPartnerPermsField = value;
                    this.RaisePropertyChanged("busPartnerPerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.ChannelPermQuery[] channelPerms {
            get {
                return this.channelPermsField;
            }
            set {
                if ((object.ReferenceEquals(this.channelPermsField, value) != true)) {
                    this.channelPermsField = value;
                    this.RaisePropertyChanged("channelPerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] mobilMarketingPerms {
            get {
                return this.mobilMarketingPermsField;
            }
            set {
                if ((object.ReferenceEquals(this.mobilMarketingPermsField, value) != true)) {
                    this.mobilMarketingPermsField = value;
                    this.RaisePropertyChanged("mobilMarketingPerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.CategoryPermQuery[] turkcellPerms {
            get {
                return this.turkcellPermsField;
            }
            set {
                if ((object.ReferenceEquals(this.turkcellPermsField, value) != true)) {
                    this.turkcellPermsField = value;
                    this.RaisePropertyChanged("turkcellPerms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryPermQuery", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class CategoryPermQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string catDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int catIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string catDesc {
            get {
                return this.catDescField;
            }
            set {
                if ((object.ReferenceEquals(this.catDescField, value) != true)) {
                    this.catDescField = value;
                    this.RaisePropertyChanged("catDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int catId {
            get {
                return this.catIdField;
            }
            set {
                if ((this.catIdField.Equals(value) != true)) {
                    this.catIdField = value;
                    this.RaisePropertyChanged("catId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptOut {
            get {
                return this.coptOutField;
            }
            set {
                if ((this.coptOutField.Equals(value) != true)) {
                    this.coptOutField = value;
                    this.RaisePropertyChanged("coptOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelPermQuery", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class ChannelPermQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int channelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string channelDesc {
            get {
                return this.channelDescField;
            }
            set {
                if ((object.ReferenceEquals(this.channelDescField, value) != true)) {
                    this.channelDescField = value;
                    this.RaisePropertyChanged("channelDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int channelId {
            get {
                return this.channelIdField;
            }
            set {
                if ((this.channelIdField.Equals(value) != true)) {
                    this.channelIdField = value;
                    this.RaisePropertyChanged("channelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptOut {
            get {
                return this.coptOutField;
            }
            set {
                if ((this.coptOutField.Equals(value) != true)) {
                    this.coptOutField = value;
                    this.RaisePropertyChanged("coptOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermQueryArrResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermQueryArrResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.ArrayOfString permArrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.ArrayOfString permArr {
            get {
                return this.permArrField;
            }
            set {
                if ((object.ReferenceEquals(this.permArrField, value) != true)) {
                    this.permArrField = value;
                    this.RaisePropertyChanged("permArr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalBulkWrite", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalBulkWrite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteRecord[] approvalRequestListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteRecord[] approvalRequestList {
            get {
                return this.approvalRequestListField;
            }
            set {
                if ((object.ReferenceEquals(this.approvalRequestListField, value) != true)) {
                    this.approvalRequestListField = value;
                    this.RaisePropertyChanged("approvalRequestList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalBulkWriteRecord", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalBulkWriteRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long approvalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal long approvalType {
            get {
                return this.approvalTypeField;
            }
            set {
                if ((this.approvalTypeField.Equals(value) != true)) {
                    this.approvalTypeField = value;
                    this.RaisePropertyChanged("approvalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string approveDate {
            get {
                return this.approveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.approveDateField, value) != true)) {
                    this.approveDateField = value;
                    this.RaisePropertyChanged("approveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalBulkWriteResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalBulkWriteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteResultRecord[] requestResultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteResultRecord[] requestResultList {
            get {
                return this.requestResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.requestResultListField, value) != true)) {
                    this.requestResultListField = value;
                    this.RaisePropertyChanged("requestResultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalBulkWriteResultRecord", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalBulkWriteResultRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermWriteArrResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermWriteArrResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.ArrayOfString permArrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.ArrayOfString permArr {
            get {
                return this.permArrField;
            }
            set {
                if ((object.ReferenceEquals(this.permArrField, value) != true)) {
                    this.permArrField = value;
                    this.RaisePropertyChanged("permArr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalWriteResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalWriteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermWriteNotificationResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermWriteNotificationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermCheckResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermCheckResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptout {
            get {
                return this.coptoutField;
            }
            set {
                if ((this.coptoutField.Equals(value) != true)) {
                    this.coptoutField = value;
                    this.RaisePropertyChanged("coptout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryPerm", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class CategoryPerm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int catIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int catId {
            get {
                return this.catIdField;
            }
            set {
                if ((this.catIdField.Equals(value) != true)) {
                    this.catIdField = value;
                    this.RaisePropertyChanged("catId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptOut {
            get {
                return this.coptOutField;
            }
            set {
                if ((this.coptOutField.Equals(value) != true)) {
                    this.coptOutField = value;
                    this.RaisePropertyChanged("coptOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelPerm", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class ChannelPerm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int channelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int coptOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int channelId {
            get {
                return this.channelIdField;
            }
            set {
                if ((this.channelIdField.Equals(value) != true)) {
                    this.channelIdField = value;
                    this.RaisePropertyChanged("channelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int coptOut {
            get {
                return this.coptOutField;
            }
            set {
                if ((this.coptOutField.Equals(value) != true)) {
                    this.coptOutField = value;
                    this.RaisePropertyChanged("coptOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalQueryResult", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wSrvConnector.PermissionServicesStb2.PermApprovalQueryRecord[] approvalListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal wSrvConnector.PermissionServicesStb2.PermApprovalQueryRecord[] approvalList {
            get {
                return this.approvalListField;
            }
            set {
                if ((object.ReferenceEquals(this.approvalListField, value) != true)) {
                    this.approvalListField = value;
                    this.RaisePropertyChanged("approvalList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermApprovalQueryRecord", Namespace="http://ws.model.data.permission.ccrl.cusman.turkcell.com")]
    [System.SerializableAttribute()]
    internal partial class PermApprovalQueryRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approvalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long approvalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string approvalDate {
            get {
                return this.approvalDateField;
            }
            set {
                if ((object.ReferenceEquals(this.approvalDateField, value) != true)) {
                    this.approvalDateField = value;
                    this.RaisePropertyChanged("approvalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal long approvalType {
            get {
                return this.approvalTypeField;
            }
            set {
                if ((this.approvalTypeField.Equals(value) != true)) {
                    this.approvalTypeField = value;
                    this.RaisePropertyChanged("approvalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.permission.ccrl.cusman.turkcell.com", ConfigurationName="PermissionServicesStb2.PermissionWebServicePortType")]
    internal interface PermissionWebServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryExtResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryExtResult queryServicePermNcstBasedExt(long ncst, int csrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeCategoryPerm(string msisdn, int msgCat, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermCorpOffline(wSrvConnector.PermissionServicesStb2.ArrayOfString ncstArr, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryResult queryServicePerm(string msisdn, int csrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryExtResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryExtResult getServicePerm(string msisdn, int csrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="AdvertisementPerm")]
        wSrvConnector.PermissionServicesStb2.AdvertisementPerm getAdvertisementPerm(long nprd);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryArrResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryArrResult checkPermAndQuotaArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int msgCat, int quotaCat, int quotaChannel, int quotaPeriod, int checkQuota, int dropQuota, int checkPerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermApprovalBulkWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteResult writeApprovalBulk(wSrvConnector.PermissionServicesStb2.PermApprovalBulkWrite PermApprovalBulkWrite, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryExtResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryExtResult getServicePermWithSms(string msisdn, int csrv, int sendSms, int csource);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteArrResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeFirsatPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteArrResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeServicePermMultiSrvArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryResult queryChannelPerm(string nprd, string msisdn, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryArrResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryServicePermMultiSrvArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnCsrvArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeTurkcellPerm(string msisdn, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermApprovalWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermApprovalWriteResult writeApproval(string msisdn, long companyId, long approvalType, int status, string approvalDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteArrResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeServicePermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csrv, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryResult queryCategoryPerm(string msisdn, int msgCat);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryArrResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryChannelPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryArrResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryCategoryPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int msgCat);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryResult queryBulkSmsPerm(string alphanumeric, string msisdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteNotificationResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteNotificationResult writeServicePermWithNotification(string msisdn, int csrv, int coptout, int csource, string userName, int forAllMsisdn, int sendSMSNotification);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermCheckResult")]
        wSrvConnector.PermissionServicesStb2.PermCheckResult checkPermAndQuota(string msisdn, int msgCat, int quotaCat, int quotaChannel, int quotaPeriod, int checkQuota, int dropQuota, int checkPerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeAdvertisementPerm(long nprd, wSrvConnector.PermissionServicesStb2.CategoryPerm[] categoryPerms, wSrvConnector.PermissionServicesStb2.ChannelPerm[] channelPerms, int bulkSmsPerm, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult deleteAlfanumeric(string alphanumeric, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeFirsatPerm(string msisdn, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermCorpOfflineByType(wSrvConnector.PermissionServicesStb2.ArrayOfString ncstArr, int coptout, int csource, string userName, int cpermType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermApprovalQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermApprovalQueryResult queryApproval(string msisdn, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult insertAlfanumeric(string alphanumeric, long ncst, int serviceId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermNcstBased(long ncst, int csrv, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermWriteResult")]
        wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePerm(string msisdn, int csrv, int coptout, int csource, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryArrResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryServicePermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csrv);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PermQueryResult")]
        wSrvConnector.PermissionServicesStb2.PermQueryResult queryServicePermNcstBased(long ncst, int csrv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface PermissionWebServicePortTypeChannel : wSrvConnector.PermissionServicesStb2.PermissionWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class PermissionWebServicePortTypeClient : System.ServiceModel.ClientBase<wSrvConnector.PermissionServicesStb2.PermissionWebServicePortType>, wSrvConnector.PermissionServicesStb2.PermissionWebServicePortType {
        
        public PermissionWebServicePortTypeClient() {
        }
        
        public PermissionWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PermissionWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PermissionWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PermissionWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryExtResult queryServicePermNcstBasedExt(long ncst, int csrv) {
            return base.Channel.queryServicePermNcstBasedExt(ncst, csrv);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeCategoryPerm(string msisdn, int msgCat, int coptout, int csource, string userName) {
            return base.Channel.writeCategoryPerm(msisdn, msgCat, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermCorpOffline(wSrvConnector.PermissionServicesStb2.ArrayOfString ncstArr, int coptout, int csource, string userName) {
            return base.Channel.writeServicePermCorpOffline(ncstArr, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryResult queryServicePerm(string msisdn, int csrv) {
            return base.Channel.queryServicePerm(msisdn, csrv);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryExtResult getServicePerm(string msisdn, int csrv) {
            return base.Channel.getServicePerm(msisdn, csrv);
        }
        
        public wSrvConnector.PermissionServicesStb2.AdvertisementPerm getAdvertisementPerm(long nprd) {
            return base.Channel.getAdvertisementPerm(nprd);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryArrResult checkPermAndQuotaArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int msgCat, int quotaCat, int quotaChannel, int quotaPeriod, int checkQuota, int dropQuota, int checkPerm) {
            return base.Channel.checkPermAndQuotaArr(msisdnArr, msgCat, quotaCat, quotaChannel, quotaPeriod, checkQuota, dropQuota, checkPerm);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermApprovalBulkWriteResult writeApprovalBulk(wSrvConnector.PermissionServicesStb2.PermApprovalBulkWrite PermApprovalBulkWrite, long companyId) {
            return base.Channel.writeApprovalBulk(PermApprovalBulkWrite, companyId);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryExtResult getServicePermWithSms(string msisdn, int csrv, int sendSms, int csource) {
            return base.Channel.getServicePermWithSms(msisdn, csrv, sendSms, csource);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeFirsatPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int coptout, int csource, string userName) {
            return base.Channel.writeFirsatPermArr(msisdnArr, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeServicePermMultiSrvArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csource, string userName) {
            return base.Channel.writeServicePermMultiSrvArr(msisdnArr, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryResult queryChannelPerm(string nprd, string msisdn, int channelId) {
            return base.Channel.queryChannelPerm(nprd, msisdn, channelId);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryServicePermMultiSrvArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnCsrvArr) {
            return base.Channel.queryServicePermMultiSrvArr(msisdnCsrvArr);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeTurkcellPerm(string msisdn, int coptout, int csource, string userName) {
            return base.Channel.writeTurkcellPerm(msisdn, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermApprovalWriteResult writeApproval(string msisdn, long companyId, long approvalType, int status, string approvalDate) {
            return base.Channel.writeApproval(msisdn, companyId, approvalType, status, approvalDate);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteArrResult writeServicePermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csrv, int coptout, int csource, string userName) {
            return base.Channel.writeServicePermArr(msisdnArr, csrv, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryResult queryCategoryPerm(string msisdn, int msgCat) {
            return base.Channel.queryCategoryPerm(msisdn, msgCat);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryChannelPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int channelId) {
            return base.Channel.queryChannelPermArr(msisdnArr, channelId);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryCategoryPermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int msgCat) {
            return base.Channel.queryCategoryPermArr(msisdnArr, msgCat);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryResult queryBulkSmsPerm(string alphanumeric, string msisdn) {
            return base.Channel.queryBulkSmsPerm(alphanumeric, msisdn);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteNotificationResult writeServicePermWithNotification(string msisdn, int csrv, int coptout, int csource, string userName, int forAllMsisdn, int sendSMSNotification) {
            return base.Channel.writeServicePermWithNotification(msisdn, csrv, coptout, csource, userName, forAllMsisdn, sendSMSNotification);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermCheckResult checkPermAndQuota(string msisdn, int msgCat, int quotaCat, int quotaChannel, int quotaPeriod, int checkQuota, int dropQuota, int checkPerm) {
            return base.Channel.checkPermAndQuota(msisdn, msgCat, quotaCat, quotaChannel, quotaPeriod, checkQuota, dropQuota, checkPerm);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeAdvertisementPerm(long nprd, wSrvConnector.PermissionServicesStb2.CategoryPerm[] categoryPerms, wSrvConnector.PermissionServicesStb2.ChannelPerm[] channelPerms, int bulkSmsPerm, int csource, string userName) {
            return base.Channel.writeAdvertisementPerm(nprd, categoryPerms, channelPerms, bulkSmsPerm, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult deleteAlfanumeric(string alphanumeric, string userName) {
            return base.Channel.deleteAlfanumeric(alphanumeric, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeFirsatPerm(string msisdn, int coptout, int csource, string userName) {
            return base.Channel.writeFirsatPerm(msisdn, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermCorpOfflineByType(wSrvConnector.PermissionServicesStb2.ArrayOfString ncstArr, int coptout, int csource, string userName, int cpermType) {
            return base.Channel.writeServicePermCorpOfflineByType(ncstArr, coptout, csource, userName, cpermType);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermApprovalQueryResult queryApproval(string msisdn, long companyId) {
            return base.Channel.queryApproval(msisdn, companyId);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult insertAlfanumeric(string alphanumeric, long ncst, int serviceId, string userName) {
            return base.Channel.insertAlfanumeric(alphanumeric, ncst, serviceId, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePermNcstBased(long ncst, int csrv, int coptout, int csource, string userName) {
            return base.Channel.writeServicePermNcstBased(ncst, csrv, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermWriteResult writeServicePerm(string msisdn, int csrv, int coptout, int csource, string userName) {
            return base.Channel.writeServicePerm(msisdn, csrv, coptout, csource, userName);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryArrResult queryServicePermArr(wSrvConnector.PermissionServicesStb2.ArrayOfString msisdnArr, int csrv) {
            return base.Channel.queryServicePermArr(msisdnArr, csrv);
        }
        
        public wSrvConnector.PermissionServicesStb2.PermQueryResult queryServicePermNcstBased(long ncst, int csrv) {
            return base.Channel.queryServicePermNcstBased(ncst, csrv);
        }
    }
}
