//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gnc2Entities : DbContext
    {
        public Gnc2Entities()
            : base("name=Gnc2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminAuths> AdminAuths { get; set; }
        public DbSet<Admins> Admins { get; set; }
        public DbSet<AdminTransaction> AdminTransaction { get; set; }
        public DbSet<Banners> Banners { get; set; }
        public DbSet<Campaigns> Campaigns { get; set; }
        public DbSet<CatalogCategories> CatalogCategories { get; set; }
        public DbSet<Catalogs> Catalogs { get; set; }
        public DbSet<CatalogVarieties> CatalogVarieties { get; set; }
        public DbSet<Code> Code { get; set; }
        public DbSet<Invitations> Invitations { get; set; }
        public DbSet<Moduls> Moduls { get; set; }
        public DbSet<ModulTypes> ModulTypes { get; set; }
        public DbSet<PromoCodeArchives> PromoCodeArchives { get; set; }
        public DbSet<PromoCodes> PromoCodes { get; set; }
        public DbSet<PromoCodeTypes> PromoCodeTypes { get; set; }
        public DbSet<Refunds> Refunds { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<UserCampaigns> UserCampaigns { get; set; }
        public DbSet<UserOrders> UserOrders { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
