//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodeTypes
    {
        public PromoCodeTypes()
        {
            this.PromoCodes = new HashSet<PromoCodes>();
        }
    
        public int Id { get; set; }
        public string PromoCodeTypeName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<PromoCodes> PromoCodes { get; set; }
    }
}
