//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public int Id { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string RegisterType { get; set; }
        public string LoginType { get; set; }
        public string Msisdn { get; set; }
    }
}
