//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnc2.Service.ServiceUserManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyUserLogin", Namespace="http://schemas.datacontract.org/2004/07/w2.Service.Gigya.Socialize.CustomModels")]
    [System.SerializableAttribute()]
    public partial class NotifyUserLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsisdnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cid {
            get {
                return this.CidField;
            }
            set {
                if ((object.ReferenceEquals(this.CidField, value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msisdn {
            get {
                return this.MsisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.MsisdnField, value) != true)) {
                    this.MsisdnField = value;
                    this.RaisePropertyChanged("Msisdn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Service.Gigya")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallIdField, value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyUserLoginResponse", Namespace="http://schemas.datacontract.org/2004/07/w2.Service.Gigya.Socialize.CustomModels")]
    [System.SerializableAttribute()]
    public partial class NotifyUserLoginResponse : Gnc2.Service.ServiceUserManagement.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDSignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msisdn {
            get {
                return this.MsisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.MsisdnField, value) != true)) {
                    this.MsisdnField = value;
                    this.RaisePropertyChanged("Msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureTimestamp {
            get {
                return this.SignatureTimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureTimestampField, value) != true)) {
                    this.SignatureTimestampField = value;
                    this.RaisePropertyChanged("SignatureTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIDSignature {
            get {
                return this.UIDSignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDSignatureField, value) != true)) {
                    this.UIDSignatureField = value;
                    this.RaisePropertyChanged("UIDSignature");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUserManagement.IUserManagement")]
    public interface IUserManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Login", ReplyAction="http://tempuri.org/IUserManagement/LoginResponse")]
        Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse Login(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Login", ReplyAction="http://tempuri.org/IUserManagement/LoginResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse> LoginAsync(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo);
        
        // CODEGEN: Generating message contract since the wrapper name (Json_x002F_Login) of message Json_x002F_LoginRequest does not match the default value (JsonLogin)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Json/Login", ReplyAction="http://tempuri.org/IUserManagement/Json/LoginResponse")]
        Gnc2.Service.ServiceUserManagement.JsonLoginResponse JsonLogin(Gnc2.Service.ServiceUserManagement.JsonLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Json/Login", ReplyAction="http://tempuri.org/IUserManagement/Json/LoginResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonLoginResponse> JsonLoginAsync(Gnc2.Service.ServiceUserManagement.JsonLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Register", ReplyAction="http://tempuri.org/IUserManagement/RegisterResponse")]
        Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse Register(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Register", ReplyAction="http://tempuri.org/IUserManagement/RegisterResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse> RegisterAsync(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo);
        
        // CODEGEN: Generating message contract since the wrapper name (Json_x002F_Register) of message Json_x002F_RegisterRequest does not match the default value (JsonRegister)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Json/Register", ReplyAction="http://tempuri.org/IUserManagement/Json/RegisterResponse")]
        Gnc2.Service.ServiceUserManagement.JsonRegisterResponse JsonRegister(Gnc2.Service.ServiceUserManagement.JsonRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/Json/Register", ReplyAction="http://tempuri.org/IUserManagement/Json/RegisterResponse")]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonRegisterResponse> JsonRegisterAsync(Gnc2.Service.ServiceUserManagement.JsonRegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonLoginRequest {
        
        public JsonLoginRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonLoginResponse {
        
        public JsonLoginResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/Register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonRegisterRequest {
        
        public JsonRegisterRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Json/RegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JsonRegisterResponse {
        
        public JsonRegisterResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementChannel : Gnc2.Service.ServiceUserManagement.IUserManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<Gnc2.Service.ServiceUserManagement.IUserManagement>, Gnc2.Service.ServiceUserManagement.IUserManagement {
        
        public UserManagementClient() {
        }
        
        public UserManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse Login(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo) {
            return base.Channel.Login(userInfo);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse> LoginAsync(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo) {
            return base.Channel.LoginAsync(userInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gnc2.Service.ServiceUserManagement.JsonLoginResponse Gnc2.Service.ServiceUserManagement.IUserManagement.JsonLogin(Gnc2.Service.ServiceUserManagement.JsonLoginRequest request) {
            return base.Channel.JsonLogin(request);
        }
        
        public void JsonLogin() {
            Gnc2.Service.ServiceUserManagement.JsonLoginRequest inValue = new Gnc2.Service.ServiceUserManagement.JsonLoginRequest();
            Gnc2.Service.ServiceUserManagement.JsonLoginResponse retVal = ((Gnc2.Service.ServiceUserManagement.IUserManagement)(this)).JsonLogin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonLoginResponse> Gnc2.Service.ServiceUserManagement.IUserManagement.JsonLoginAsync(Gnc2.Service.ServiceUserManagement.JsonLoginRequest request) {
            return base.Channel.JsonLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonLoginResponse> JsonLoginAsync() {
            Gnc2.Service.ServiceUserManagement.JsonLoginRequest inValue = new Gnc2.Service.ServiceUserManagement.JsonLoginRequest();
            return ((Gnc2.Service.ServiceUserManagement.IUserManagement)(this)).JsonLoginAsync(inValue);
        }
        
        public Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse Register(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo) {
            return base.Channel.Register(userInfo);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.NotifyUserLoginResponse> RegisterAsync(Gnc2.Service.ServiceUserManagement.NotifyUserLogin userInfo) {
            return base.Channel.RegisterAsync(userInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gnc2.Service.ServiceUserManagement.JsonRegisterResponse Gnc2.Service.ServiceUserManagement.IUserManagement.JsonRegister(Gnc2.Service.ServiceUserManagement.JsonRegisterRequest request) {
            return base.Channel.JsonRegister(request);
        }
        
        public void JsonRegister() {
            Gnc2.Service.ServiceUserManagement.JsonRegisterRequest inValue = new Gnc2.Service.ServiceUserManagement.JsonRegisterRequest();
            Gnc2.Service.ServiceUserManagement.JsonRegisterResponse retVal = ((Gnc2.Service.ServiceUserManagement.IUserManagement)(this)).JsonRegister(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonRegisterResponse> Gnc2.Service.ServiceUserManagement.IUserManagement.JsonRegisterAsync(Gnc2.Service.ServiceUserManagement.JsonRegisterRequest request) {
            return base.Channel.JsonRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gnc2.Service.ServiceUserManagement.JsonRegisterResponse> JsonRegisterAsync() {
            Gnc2.Service.ServiceUserManagement.JsonRegisterRequest inValue = new Gnc2.Service.ServiceUserManagement.JsonRegisterRequest();
            return ((Gnc2.Service.ServiceUserManagement.IUserManagement)(this)).JsonRegisterAsync(inValue);
        }
    }
}
